on:
  schedules:
  - cron: 0 0 1 * *
name: Check HTML links
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -d . -r .
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_TITLE: Link Checker Report
        ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
        ISSUE_LABELS: report, automated issue
