name: CI

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Link Checker
        uses: peter-evans/link-checker@v1
        with:
          args: -v -d . -r $PWD/
      - name: debug
        run: pwd && ls
