name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate HTML5
        uses: Cyb3r-Jak3/html5validator-action@v0.1
        with:
          root: .
