name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Link Checker
        uses: peter-evans/link-checker@v1
        with:
          args: -v -d . -r .
